server:
  port: 8200

spring:
  profiles:
    active: @profile@

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://45.32.136.68:3306/distance
    username: root
    password: Root123.

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      idle-timeout: 12000
      connection-timeout: 30000
      max-lifetime: 30000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

